<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LIN-PF1TL17Q" failures="1" tests="5" name="Personal Loan" time="0.186" errors="0" timestamp="2024-04-04T10:47:23 IST">
  <testcase classname="test.day1" name="Demo" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day2" name="ploan" time="0.003"/>
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.004"/>
  <testcase classname="test.day4" name="MobileloginHomeLoan" time="0.004"/>
  <testcase classname="test.day4" name="WebloginHomeLoan" time="0.004"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
